--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Poustmal/ShulkerBall
branches:
- master
projects:
  ShulkerBall:
    path: ""
    icon: "https://raw.githubusercontent.com/Poustmal/ShulkerBall/master/ShulkerBall.jpg"
...
